#!/bin/bash

#SBATCH --partition=gpu_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=IR2_Model_Training
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=1:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2019
module load Anaconda3/2018.12

# Your job starts in the directory where you call sbatch
cd $HOME/ir2
# Activate your environment
source activate ir2
# Run your code
srun python -u huggingface/train_dpr_huggingface.py --model bert